

#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FFLr --task finance_forecast --in_len 134 --out_len 33 --hidden_dim 32 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FFLr --task finance_forecast --in_len 134 --out_len 33 --hidden_dim 32 --checkpoint_path output/MiTransformer_FFLr/ts_encoder_epoch7.pt --dataset_path ./data/processed/finance/long/test --ts_encoder MiTransformer --use_bfloat16 --eval_mode full_test
#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --output_dir output/MiTransformer_FFS --task finance_forecast --in_len 312 --out_len 78 --hidden_dim 32 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --output_dir output/MiTransformer_FFS --task finance_forecast --in_len 312 --out_len 78 --hidden_dim 32 --checkpoint_path output/MiTransformer_FFS/ts_encoder_epoch6.pt --dataset_path ./data/processed/finance/short/test --ts_encoder MiTransformer --use_bfloat16 --eval_mode full_test


#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FFLr --task finance_forecast --in_len 134 --out_len 33 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FFLr --task finance_forecast --in_len 134 --out_len 33 --checkpoint_path output/mmlinear_FFLr/ts_encoder_epoch7.pt --dataset_path ./data/processed/finance/long/test --ts_encoder mmlinear --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FFSr --task finance_forecast --in_len 312 --out_len 78 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FFSr --task finance_forecast --in_len 312 --out_len 78 --checkpoint_path output/mmlinear_FFSr/ts_encoder_epoch6.pt --dataset_path ./data/processed/finance/short/test --ts_encoder mmlinear --use_bfloat16 --eval_mode full_test


#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTLr3 --task finance_trend_prediction --in_len 134 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MoMe --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTLr3 --task finance_trend_prediction --in_len 134 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --patch_len 8 --checkpoint_path output/MoME_FTLr3/ts_encoder_epoch9.pt --dataset_path ./data/processed/finance/long/test --ts_encoder MoMe --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTSr3 --task finance_trend_prediction --in_len 312 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MoMe --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTSr3 --task finance_trend_prediction --in_len 312 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --patch_len 8 --checkpoint_path output/MoME_FTSr3/ts_encoder_epoch9.pt --dataset_path ./data/processed/finance/short/test --ts_encoder MoMe --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTLr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MoMe --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTLr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --patch_len 8 --checkpoint_path output/MoME_FTLr5/ts_encoder_epoch9.pt --dataset_path ./data/processed/finance/long/test --ts_encoder MoMe --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTSr5 --task finance_trend_prediction --in_len 312 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MoMe --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTSr5 --task finance_trend_prediction --in_len 312 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --patch_len 8 --checkpoint_path output/MoME_FTSr5/ts_encoder_epoch9.pt --dataset_path ./data/processed/finance/short/test --ts_encoder MoMe --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTLr3 --task finance_trend_prediction --in_len 134 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTLr3 --task finance_trend_prediction --in_len 134 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --checkpoint_path output/MiTransformer_FTLr3/ts_encoder_epoch9.pt --dataset_path ./data/processed/finance/long/test --ts_encoder MiTransformer --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTSr3 --task finance_trend_prediction --in_len 312 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTSr3 --task finance_trend_prediction --in_len 312 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --checkpoint_path output/MiTransformer_FTSr3/ts_encoder_epoch9.pt --dataset_path ./data/processed/finance/short/test --ts_encoder MiTransformer --use_bfloat16 --eval_mode full_test


#CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTLr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTLr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --checkpoint_path output/MiTransformer_FTLr5/ts_encoder_epoch8.pt --dataset_path ./data/processed/finance/long/test --ts_encoder MiTransformer --use_bfloat16 --eval_mode full_test


#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --output_dir output/MiTransformer_FTS5 --task finance_trend_prediction --in_len 312 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=3 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --output_dir output/MiTransformer_FTS5 --task finance_trend_prediction --in_len 312 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --checkpoint_path output/MiTransformer_FTS5/ts_encoder_epoch8.pt --dataset_path ./data/processed/finance/short/test --ts_encoder MiTransformer --use_bfloat16 --eval_mode full_test


#CUDA_VISIBLE_DEVICES=0 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTLr3 --task finance_trend_prediction --in_len 134 --out_len 3 --finance_trend_choice 3way --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
#CUDA_VISIBLE_DEVICES=0 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTLr3 --task finance_trend_prediction --in_len 134 --out_len 3 --finance_trend_choice 3way --checkpoint_path output/mmlinear_FTLr3/ts_encoder_epoch9.pt --dataset_path ./data/processed/finance/long/test --ts_encoder mmlinear --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=0 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTSr3 --task finance_trend_prediction --in_len 312 --out_len 3 --finance_trend_choice 3way --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
#CUDA_VISIBLE_DEVICES=0 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTSr3 --task finance_trend_prediction --in_len 312 --out_len 3 --finance_trend_choice 3way --checkpoint_path output/mmlinear_FTSr3/ts_encoder_epoch9.pt --dataset_path ./data/processed/finance/short/test --ts_encoder mmlinear --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=0 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTLr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
#CUDA_VISIBLE_DEVICES=0 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTLr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --checkpoint_path output/mmlinear_FTLr5/ts_encoder_epoch7.pt --dataset_path ./data/processed/finance/long/test --ts_encoder mmlinear --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=0 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTSr5 --task finance_trend_prediction --in_len 312 --out_len 5 --finance_trend_choice 5way --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
#CUDA_VISIBLE_DEVICES=0 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTSr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --checkpoint_path output/mmlinear_FTLr5/ts_encoder_epoch7.pt --dataset_path ./data/processed/finance/long/test --ts_encoder mmlinear --use_bfloat16 --eval_mode full_test
