
#CUDA_VISIBLE_DEVICES=2 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WFSr --task weather_forecast --in_len 168 --out_len 24 --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/weather/short/train --epochs 10 --ts_encoder MoMe --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WFLr --task weather_forecast --in_len 336 --out_len 72 --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/weather/long/train --epochs 10 --ts_encoder MoMe --use_bfloat16

#CUDA_VISIBLE_DEVICES=2 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WFLr --task weather_forecast --in_len 168 --out_len 24 --hidden_dim 32 --dataset_path ./data/processed/weather/short/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WFSr --task weather_forecast --in_len 336 --out_len 72 --hidden_dim 32 --dataset_path ./data/processed/weather/long/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16

#CUDA_VISIBLE_DEVICES=2 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WFLr --task weather_forecast --in_len 168 --out_len 24 --dataset_path ./data/processed/weather/short/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WFSr --task weather_forecast --in_len 336 --out_len 72 --dataset_path ./data/processed/weather/long/train --epochs 10 --ts_encoder mmlinear --use_bfloat16


#CUDA_VISIBLE_DEVICES=2 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WTSrp --task weather_trend_prediction --weather_trend_choice past --in_len 168 --out_len 3 --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/weather/short/train --epochs 10 --ts_encoder MoMe --use_bfloat16
#CUDA_VISIBLE_DEVICES=0 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WTSrp --task weather_trend_prediction --weather_trend_choice past --in_len 168 --out_len 3 --hidden_dim 32 --patch_len 8  --checkpoint_path output/MoME_WTSrp/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/short/test --ts_encoder MoMe --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WTLrp --task weather_trend_prediction --weather_trend_choice past --in_len 336 --out_len 3 --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/weather/long/train --epochs 10 --ts_encoder MoMe --use_bfloat16
#CUDA_VISIBLE_DEVICES=0 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WTLrp --task weather_trend_prediction --weather_trend_choice past --in_len 336 --out_len 3 --hidden_dim 32 --patch_len 8  --checkpoint_path output/MoME_WTLrp/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/long/test --ts_encoder MoMe --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WTSrf --task weather_trend_prediction --weather_trend_choice future --in_len 168 --out_len 3 --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/weather/short/train --epochs 10 --ts_encoder MoMe --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WTSrf --task weather_trend_prediction --weather_trend_choice future --in_len 168 --out_len 3 --hidden_dim 32 --patch_len 8  --checkpoint_path output/MoME_WTSrf/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/short/test --ts_encoder MoMe --use_bfloat16 --eval_mode full_test

#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WTLrf --task weather_trend_prediction --weather_trend_choice future --in_len 336 --out_len 3 --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/weather/long/train --epochs 10 --ts_encoder MoMe --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_WTLrf --task weather_trend_prediction --weather_trend_choice future --in_len 336 --out_len 3 --hidden_dim 32 --patch_len 8  --checkpoint_path output/MoME_WTLrf/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/long/test --ts_encoder MoMe --use_bfloat16 --eval_mode full_test


#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WTLrp --task weather_trend_prediction --weather_trend_choice past --in_len 168 --out_len 3 --hidden_dim 32 --dataset_path ./data/processed/weather/short/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WTLrp --task weather_trend_prediction --weather_trend_choice past --in_len 168 --out_len 3 --hidden_dim 32  --checkpoint_path output/MiTransformer_WTLrp/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/short/test --ts_encoder MiTransformer --use_bfloat16 --eval_mode full_test


#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WTSrp --task weather_trend_prediction --weather_trend_choice past --in_len 336 --out_len 3 --hidden_dim 32 --dataset_path ./data/processed/weather/long/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WTSrp --task weather_trend_prediction --weather_trend_choice past --in_len 336 --out_len 3 --hidden_dim 32  --checkpoint_path output/MiTransformer_WTSrp/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/long/test --ts_encoder MiTransformer --use_bfloat16 --eval_mode full_test


#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WTLrf --task weather_trend_prediction --weather_trend_choice future --in_len 168 --out_len 3 --hidden_dim 32 --dataset_path ./data/processed/weather/short/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WTLrf --task weather_trend_prediction --weather_trend_choice future --in_len 168 --out_len 3 --hidden_dim 32  --checkpoint_path output/MiTransformer_WTLrf/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/short/test --ts_encoder MiTransformer --use_bfloat16 --eval_mode full_test # This is short actually

#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WTSrf --task weather_trend_prediction --weather_trend_choice future --in_len 336 --out_len 3 --hidden_dim 32 --dataset_path ./data/processed/weather/long/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_WTSrf --task weather_trend_prediction --weather_trend_choice future --in_len 336 --out_len 3 --hidden_dim 32  --checkpoint_path output/MiTransformer_WTSrf/ts_encoder_epoch4.pt --dataset_path ./data/processed/weather/long/test --ts_encoder MiTransformer --use_bfloat16 # This is long actually



#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WTLrp --task weather_trend_prediction --weather_trend_choice past --in_len 168 --out_len 3 --dataset_path ./data/processed/weather/short/train --epochs 10 --ts_encoder mmlinear --use_bfloat16  #This is long
#CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WTLrp --task weather_trend_prediction --weather_trend_choice past --in_len 168 --out_len 3  --checkpoint_path output/mmlinear_WTLrp/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/short/test --ts_encoder mmlinear --use_bfloat16 # This is short

#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WTSrp --task weather_trend_prediction --weather_trend_choice past --in_len 336 --out_len 3 --dataset_path ./data/processed/weather/long/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
#CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WTSrp --task weather_trend_prediction --weather_trend_choice past --in_len 336 --out_len 3  --checkpoint_path output/mmlinear_WTSrp/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/long/test --ts_encoder mmlinear --use_bfloat16 # This is long

#CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WTLrf --task weather_trend_prediction --weather_trend_choice future --in_len 168 --out_len 3 --dataset_path ./data/processed/weather/short/train --epochs 10 --ts_encoder mmlinear --use_bfloat16 #This is long
#CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WTLrf --task weather_trend_prediction --weather_trend_choice future --in_len 168 --out_len 3  --checkpoint_path output/mmlinear_WTLrf/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/short/test --ts_encoder mmlinear --use_bfloat16 # This is short

CUDA_VISIBLE_DEVICES=3 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WTSrf --task weather_trend_prediction --weather_trend_choice future --in_len 336 --out_len 3 --dataset_path ./data/processed/weather/long/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
CUDA_VISIBLE_DEVICES=2 python evaluate.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_WTSrf --task weather_trend_prediction --weather_trend_choice future --in_len 336 --out_len 3  --checkpoint_path output/mmlinear_WTSrf/ts_encoder_epoch5.pt --dataset_path ./data/processed/weather/long/test --ts_encoder mmlinear --use_bfloat16 # This is long
