

CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FFLr --task finance_forecast --in_len 134 --out_len 33 --hidden_dim 32 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FFSr --task finance_forecast --in_len 312 --out_len 78 --hidden_dim 32 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16

CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FFLr --task finance_forecast --in_len 134 --out_len 33 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FFSr --task finance_forecast --in_len 312 --out_len 78 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder mmlinear --use_bfloat16


CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTLr3 --task finance_trend_prediction --in_len 134 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MoMe --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTSr3 --task finance_trend_prediction --in_len 312 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MoMe --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTLr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MoMe --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MoME_FTSr5 --task finance_trend_prediction --in_len 312 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --patch_len 8 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MoMe --use_bfloat16

CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTLr3 --task finance_trend_prediction --in_len 134 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTSr3 --task finance_trend_prediction --in_len 312 --out_len 3 --finance_trend_choice 3way --hidden_dim 32 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTLr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/MiTransformer_FTSr5 --task finance_trend_prediction --in_len 312 --out_len 5 --finance_trend_choice 5way --hidden_dim 32 --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder MiTransformer --use_bfloat16

CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTLr3 --task finance_trend_prediction --in_len 134 --out_len 3 --finance_trend_choice 3way --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTSr3 --task finance_trend_prediction --in_len 312 --out_len 3 --finance_trend_choice 3way --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTLr5 --task finance_trend_prediction --in_len 134 --out_len 5 --finance_trend_choice 5way --dataset_path ./data/processed/finance/long/train --epochs 10 --ts_encoder mmlinear --use_bfloat16
CUDA_VISIBLE_DEVICES=1 python train.py --instructor_query 3 --n_experts 4 --topk 2 --modulation --router_modulation --output_dir output/mmlinear_FTSr5 --task finance_trend_prediction --in_len 312 --out_len 5 --finance_trend_choice 5way --dataset_path ./data/processed/finance/short/train --epochs 10 --ts_encoder mmlinear --use_bfloat16